#!/usr/bin/env bash
# GuardAsli — تنها منبع حقیقتِ پیکربندی nginx
# Product: GuardAsli · Developer: AsliCode · Coded by AsliCode
#
# هر مسیر نصب/آپدیت/SSL از همین فایل استفاده می‌کند، پس پورت‌های نقش هیچ‌وقت
# گم نمی‌شوند: پورت ۸۰ (کاربر عادی) · ۱۰۵ (نماینده) · ۶۱۶ (سوپر ادمین)
#
# ورودی (env):
#   GA_DOMAIN         دامنه (اجباری)
#   GA_PORT_UI        پورت داخلی اپ (پیش‌فرض 4173)
#   GA_PORT_RESELLER  پورت ورود نماینده (پیش‌فرض 105)
#   GA_PORT_SUPER     پورت ورود سوپر ادمین (پیش‌فرض 616)
#   GA_WEBROOT        ریشه‌ی چالش ACME (پیش‌فرض /var/www/html)
#   GA_TLS=0|1        اجبار HTTPS روی پورت‌های نقش
#   GA_ETC            ریشه‌ی nginx (پیش‌فرض /etc/nginx) — برای تست
#   GA_CERT_DIR       مسیر گواهی (پیش‌فرض /etc/letsencrypt/live/<دامنه>)
#
# نکته‌ی کلیدی: certbot فایل ما را دست نمی‌زند (certonly + webroot). بعد از
# گرفتن گواهی، همین اسکریپت دوباره اجرا می‌شود و این‌بار TLS را روی هر سه
# پورت روشن می‌کند — چیزی که certbot --nginx هرگز انجام نمی‌دهد.
set -uo pipefail

DOMAIN="${GA_DOMAIN:-${GUARDASLI_MAIN_DOMAIN:-}}"
PORT_UI="${GA_PORT_UI:-4173}"
PORT_RESELLER="${GA_PORT_RESELLER:-105}"
PORT_SUPER="${GA_PORT_SUPER:-616}"
WEBROOT="${GA_WEBROOT:-/var/www/html}"
TLS="${GA_TLS:-auto}"
ETC="${GA_ETC:-/etc/nginx}"

SITES_DIR="${ETC}/sites-available"
SITES_LIVE="${ETC}/sites-enabled"
CONF="${SITES_DIR}/guardasli"
MAP_SRC="$(cd "$(dirname "${BASH_SOURCE[0]}")/../deploy/nginx" 2>/dev/null && pwd)/guardasli-map.conf" || MAP_SRC=""

log() { printf '[nginx] %s\n' "$*"; }
die() { printf '[nginx] ERROR: %s\n' "$*" >&2; exit 1; }

[ -n "${DOMAIN}" ] || die "GA_DOMAIN is required"

# گواهی معتبر؟ اگر هست TLS را روی همه‌ی پورت‌ها روشن می‌کنیم.
CERT_DIR="${GA_CERT_DIR:-/etc/letsencrypt/live/${DOMAIN}}"
HAVE_TLS=0
if [ -f "${CERT_DIR}/fullchain.pem" ] && [ -f "${CERT_DIR}/privkey.pem" ]; then
  HAVE_TLS=1
fi
if [ "${TLS}" = "0" ]; then
  HAVE_TLS=0
elif [ "${TLS}" = "1" ] && [ "${HAVE_TLS}" = "0" ]; then
  log "GA_TLS=1 but no certificate at ${CERT_DIR} — serving HTTP only"
  HAVE_TLS=0
fi

# حالت تست: وقتی ریشه‌ی nginx متفاوت است، نه به خود nginx نیاز داریم و نه
# بارگذاری مجدد واقعی — وگرنه تست‌ها به ماشین میزبان دست می‌زنند.
TEST_MODE=0
if [ "${ETC}" != "/etc/nginx" ]; then
  TEST_MODE=1
fi
[ "${TEST_MODE}" = "1" ] || { command -v nginx >/dev/null 2>&1 || die "nginx is not installed"; }
mkdir -p "${SITES_DIR}" "${SITES_LIVE}" "${WEBROOT}" "${WEBROOT}/.well-known/acme-challenge"

# ── بدنه‌ی مشترک پروکسی ─────────────────────────────────────────────────────
proxy_block() {
  cat <<'PROXY'
  # بررسی سلامت توسط `guardasli ports` (بدون نیاز به پروکسی به اپ)
  location = /nginx-health {
    access_log off;
    add_header Content-Type text/plain;
    return 200 "ok\n";
  }

  location / {
    proxy_pass http://127.0.0.1:__PORT_UI__;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;
    proxy_connect_timeout 10s;
    proxy_send_timeout 60s;
    proxy_read_timeout 60s;
  }
PROXY
}

TLS_DIRECTIVES="  ssl_certificate ${CERT_DIR}/fullchain.pem;
  ssl_certificate_key ${CERT_DIR}/privkey.pem;
  ssl_protocols TLSv1.2 TLSv1.3;
  ssl_prefer_server_ciphers off;
  ssl_session_cache shared:GuardAsli:10m;
  ssl_session_timeout 1d;
  add_header Strict-Transport-Security \"max-age=31536000\" always;"

TMP="$(mktemp)"
{
  echo "# GuardAsli — generated by scripts/nginx-render.sh (do not edit by hand)"
  echo "# Product: GuardAsli · Developer: AsliCode"
  echo "# user:${DOMAIN} reseller:${PORT_RESELLER} super-admin:${PORT_SUPER}"
  echo ""

  # ── پورت ۸۰: چالش ACME + (اگر گواهی داریم) ریدایرکت به HTTPS
  cat <<EOF
server {
  listen 80;
  server_name ${DOMAIN};
  client_max_body_size 25m;

  # چالش ACME — باید قبل از ریدایرکت بماند
  location ^~ /.well-known/acme-challenge/ {
    root ${WEBROOT};
    default_type "text/plain";
  }
EOF
  if [ "${HAVE_TLS}" = "1" ]; then
    cat <<EOF

  location / {
    return 301 https://\$host\$request_uri;
  }
}
EOF
  else
    echo ""
    proxy_block | sed "s/__PORT_UI__/${PORT_UI}/g"
    echo "}"
  fi

  # ── پورت نماینده
  if [ "${HAVE_TLS}" = "1" ]; then
    cat <<EOF

# ── ورود نمایندگان (${PORT_RESELLER}) ──
server {
  listen ${PORT_RESELLER};
  server_name ${DOMAIN};
  client_max_body_size 25m;
${TLS_DIRECTIVES}
EOF
  else
    cat <<EOF

# ── ورود نمایندگان (${PORT_RESELLER}, HTTP) ──
server {
  listen ${PORT_RESELLER};
  server_name ${DOMAIN};
  client_max_body_size 25m;
EOF
  fi
  proxy_block | sed "s/__PORT_UI__/${PORT_UI}/g"
  echo "}"

  # ── پورت سوپر ادمین
  if [ "${HAVE_TLS}" = "1" ]; then
    cat <<EOF

# ── ورود سوپر ادمین (${PORT_SUPER}) ──
server {
  listen ${PORT_SUPER};
  server_name ${DOMAIN};
  client_max_body_size 25m;
${TLS_DIRECTIVES}
EOF
  else
    cat <<EOF

# ── ورود سوپر ادمین (${PORT_SUPER}, HTTP) ──
server {
  listen ${PORT_SUPER};
  server_name ${DOMAIN};
  client_max_body_size 25m;
EOF
  fi
  proxy_block | sed "s/__PORT_UI__/${PORT_UI}/g"
  echo "}"
} > "${TMP}"

# map لازم برای websocket در http{} — اگر موجود نباشد، map ساده می‌سازیم
if [ -n "${MAP_SRC}" ] && [ -f "${MAP_SRC}" ]; then
  cp -f "${MAP_SRC}" "${ETC}/conf.d/guardasli-map.conf" 2>/dev/null || true
fi
if [ ! -f "${ETC}/conf.d/guardasli-map.conf" ]; then
  mkdir -p "${ETC}/conf.d" 2>/dev/null || true
  cat > "${ETC}/conf.d/guardasli-map.conf" <<'MAP'
map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}
MAP
fi

# ── اعمال با بازگشت به عقب ──────────────────────────────────────────────────
BACKUP=""
if [ -f "${CONF}" ]; then
  BACKUP="$(mktemp)"
  cp -f "${CONF}" "${BACKUP}"
fi
cp -f "${TMP}" "${CONF}"
ln -sf "${CONF}" "${SITES_LIVE}/guardasli"
rm -f "${SITES_LIVE}/default"

if [ "${TEST_MODE}" = "1" ]; then
  rm -f "${TMP}" "${BACKUP}"
  SCHEME_TEST="http"
  [ "${HAVE_TLS}" = "1" ] && SCHEME_TEST="https"
  log "rendered for ${DOMAIN} -> 127.0.0.1:${PORT_UI} (TLS=${HAVE_TLS}, test mode)"
  exit 0
fi

if ! nginx -t 2>/dev/null; then
  log "configuration test FAILED — rolling back"
  if [ -n "${BACKUP}" ] && [ -f "${BACKUP}" ]; then
    cp -f "${BACKUP}" "${CONF}"
  else
    rm -f "${CONF}"
  fi
  rm -f "${TMP}" "${BACKUP}"
  nginx -t >/dev/null 2>&1 && systemctl reload nginx 2>/dev/null || true
  exit 1
fi

systemctl reload nginx 2>/dev/null || systemctl restart nginx 2>/dev/null || true
rm -f "${TMP}" "${BACKUP}"

# ── فایروال ────────────────────────────────────────────────────────────────
if [ "${TEST_MODE}" = "0" ] && command -v ufw >/dev/null 2>&1; then
  ufw allow "${PORT_RESELLER}/tcp" >/dev/null 2>&1 || true
  ufw allow "${PORT_SUPER}/tcp" >/dev/null 2>&1 || true
fi

SCHEME="http"
[ "${HAVE_TLS}" = "1" ] && SCHEME="https"
log "applied for ${DOMAIN} -> 127.0.0.1:${PORT_UI} (TLS=${HAVE_TLS})"
log "  users     : ${SCHEME}://${DOMAIN}/"
log "  reseller  : ${SCHEME}://${DOMAIN}:${PORT_RESELLER}/"
log "  super     : ${SCHEME}://${DOMAIN}:${PORT_SUPER}/"
